# Data Cleaning

In [223]:
import pandas as pd
import numpy as np

In [270]:
dataframe=pd.read_csv("../final data/cap-3 student info.csv")
dataframe.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Sr.No. Merit No   Marks  \
0           0             0               0       1       60  95.13%   
1           1             1               1       2      213  93.38%   
2           2             2               2       3      384  92.47%   
3           3             3               3       4      420  92.31%   
4           4             4               4       5      846  90.79%   

  Application ID           Name of Candidate Gender Category PWD/DEF  \
0    DSE19106856  PAWAR SIDDHI RAVINDRASINGH      F     OPEN     NaN   
1    DSE19126045   MAHALLE SHRADDHA MOHANRAO      F      OBC     NaN   
2    DSE19105661        TUSHAR RAJESH LAHANE      M      OBC     NaN   
3    DSE19103256         RAUT PALASH SUBHASH      M      OBC     NaN   
4    DSE19148502   BIRAJDAR SAURABH DAYANAND      M     SEBC     NaN   

  Sub Group Seat Type  cource_code  college_code  
0       201    ^LOPEN          201          1002  
1       201    ^GOPEN          201          1002  
2       201     ^GOBC          201          1002  
3       201     ^GOBC          201          1002  
4       201    ^GSEBC          201          1002

In [271]:
dataframe.drop(["Unnamed: 0","Unnamed: 0.1"],axis=1,inplace=True)

## Feature clearing

### Feature ["Mert No"]

Marks have some vacant anoted by "-" they showd be convertd as 0  

In [272]:
dataframe["Merit No"]=dataframe["Merit No"].astype(str)
vacent_entres=dataframe[dataframe["Merit No"]=="-"].index.values
dataframe.iloc[vacent_entres]=0

The feature mert no have all the integer feature it shoud be integer

In [273]:
dataframe["Merit No"] = pd.to_numeric(dataframe["Merit No"], errors='coerce').fillna(0).astype(np.int64)

### Feature [Marks]

The marks in format of % eg 80.0% they should converted as 80.0 

In [274]:
dataframe["Marks"]=dataframe["Marks"].astype(str)

In [275]:
length=dataframe.shape
length[0]

73580

removig %

In [276]:
for i in range(length[0]):
    data=dataframe["Marks"].iloc[i]
    if data!=0:
        data=''.join([ word for word  in data if word.isdigit() or word=="."])
        dataframe["Marks"].iloc[i]=data

C:\Users\sai\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


In [277]:
dataframe["Marks"] = pd.to_numeric(dataframe["Marks"], errors='coerce').fillna(0).astype(np.float64)

### Feature [Application Id]

The application id is only the feature that can uniqly identify student bot the application id is in format DSE12458. if move remove [DSE] from the if goood o have id as Integer

In [278]:
dataframe["Application ID"]=dataframe["Application ID"].astype(str)

In [279]:
for i in range(length[0]):
    data=dataframe["Application ID"].iloc[i]
    if  data !=0:
        data=''.join([word for word in data if  word.isdigit()])
        dataframe["Application ID"].iloc[i]=data

In [280]:
dataframe["Application ID"] = pd.to_numeric(dataframe["Application ID"], errors='coerce').fillna(0).astype(np.int64)

### Feature [Seat Type]

The feature seat type contain the spacial symobols witch can affect model.It better to remove the symboles

In [281]:
dataframe["Seat Type"]=dataframe["Seat Type"].astype(str)

In [282]:
for i in range(length[0]):
    data=dataframe["Seat Type"].iloc[i]
    if data!=0:
        data=''.join([word for word in data if word.isalpha()])
        dataframe["Seat Type"].iloc[i]=data

In [283]:
dataframe["Seat Type"].unique()

array(['LOPEN', 'GOPEN', 'GOBC', 'GSEBC', 'LSC', 'EWS', 'LST', '', 'LOBC',
       'GST', 'GNTD', 'GSC', 'DFO', 'LSEBC', 'PHNTA', 'PHNTB', 'DFNTC',
       'PHO', 'GNTA', 'LNTC', 'PHNTD', 'DFNTB', 'PHOBC', 'PHSEBC', 'LNTA',
       'GNTC', 'LNTB', 'MIMH', 'GNTB', 'DFSC', 'DFOBC', 'PHST', 'MI',
       'DFNTA', 'PHSC', 'DFST', 'DFSEBC', 'DFNTD', 'PHNTC', 'LNTD'],
      dtype=object)

### Feature [Category]

The feature invalid symboles

In [238]:
for i in range(length[0]):
    data=dataframe["Category"].iloc[i]
    if data!=0:
        data=''.join([word for word in data if word.isalpha() or word.isdigit() or word == "/" or word=="(" or word==")"])
        dataframe["Category"].iloc[i]=data

In [239]:
dataframe["Category"].unique()

array(['OPEN', 'OBC', 'SEBC', 'SC', 'OPEN/EWS', 'ST', 0, 'NT1(NTB)',
       'NT3(NTD)', 'DT/VJNT(A)', 'NT2(NTC)', 'SBC', '0'], dtype=object)

In [240]:
category_unique=dict({
    "OPEN":"OPEN",
    "OBC":"OBC",
    "SEBC":"SEBC",
    "SC":"SC",
    "OPEN/EWS":"OPEN/EWS",
    "ST":"ST",
    "NT1(NTB)":"NT1",
    "NT2(NTC)":"NT2",
    "NT3(NTD)":"NT3",
    "SBC/OBC":"SBC/OBC",
    "DT/VJNT(A)":"DT/VJNT(A)",
    "SBC":"SBC"
})

dataframe["Category"]=dataframe["Category"].map(category_unique)

In [241]:
dataframe["Category"].unique()

array(['OPEN', 'OBC', 'SEBC', 'SC', 'OPEN/EWS', 'ST', nan, 'NT1', 'NT3',
       'DT/VJNT(A)', 'NT2', 'SBC'], dtype=object)

In [242]:
category_unique=dict({
    "OPEN":1,
    "OBC":2,
    "SEBC":3,
    "SC":4,
    "OPEN/EWS":5,
    "ST":6,
    "NT1":7,
    "NT2":8,
    "NT3":9,
    "SBC/OBC":10,
    "DT/VJNT(A)":11,
    "SBC":12
})
dataframe["Category id"]=dataframe["Category"].map(category_unique)

In [243]:
dataframe["Category id"] = pd.to_numeric(dataframe["Category id"], errors='coerce').fillna(0).astype(np.int64)

In [244]:
dataframe["Category id"].unique()

array([ 1,  2,  3,  4,  5,  6,  0,  7,  9, 11,  8, 12], dtype=int64)

###  Feature [Gender]

In [245]:
dataframe["Gender"]=dataframe["Gender"].astype(str)

### Feature [PWD/DEF]

PWD/DEF invalis carater such as /n /r

In [246]:
dataframe["PWD/DEF"].unique()

array([nan, 0, 'DEF2', 'DEF1', 'Low-Vision', 'Physical \r\nimpairment',
       'Locomotor \r\nDisability', '0', 'Hard of \r\nHearing',
       'Thalassemia', 'Specific \r\nLearning \r\nDisabilities', 'DEF3',
       'Cerebral \r\nPalsy', 'Blindness', 'Deaf', 'Haemophilia',
       'Muscular \r\nDystrophy', 'Intellectual \r\nDisability',
       'Physical \r\nimpairment/DEF1'], dtype=object)

In [247]:
pwd_def=dict({
  "Locomotor \r\nDisability":"Locomotor Disability",
  "Physical \r\nimpairment":"Physical impairment",
  "Hard of \r\nHearing":"Hard of Hearing",
  "Specific \r\nLearning \r\nDisabilities":"Specific Learning Disabilities",
  "Cerebral \r\nPalsy":"Cerebral Palsy",
  "Muscular \r\nDystrophy":"Muscular Dystrophy",
  "Physical \r\nimpairment/DEF1":"Physical impairment DEF1",
  "Intellectual \r\nDisability":"Intellectual Disability"
})
dataframe["PWD/DEF"]=dataframe["PWD/DEF"].map(pwd_def)

In [248]:
dataframe["PWD/DEF"].unique()

array([nan, 'Physical impairment', 'Locomotor Disability',
       'Hard of Hearing', 'Specific Learning Disabilities',
       'Cerebral Palsy', 'Muscular Dystrophy', 'Intellectual Disability',
       'Physical impairment DEF1'], dtype=object)

### Feature [Sub Group]

In [249]:
dataframe["Sub Group"]=dataframe["Sub Group"].astype(str)
for i in range(length[0]):
    code=dataframe["Sub Group"].iloc[i]
    dataframe["Sub Group"].iloc[i]=code[-3:].lower()

In [250]:
dataframe["Sub Group"].unique()

array(['201', '101', '0', '102', '401', '103', '701', '702', '404', '301',
       '304', '104', '302', '1.0', '402', '501', '303', '305', '403',
       '601'], dtype=object)

In [251]:
dataframe["Sub Group"] = pd.to_numeric(dataframe["Sub Group"], errors='coerce').fillna(0).astype(np.int64)

### Add College Name

The data scource only have college code we have to add collage name

In [252]:
college_data=pd.read_csv("../final data/college maping.csv",index_col=["Institute Code"],usecols=None,)
college_data.drop(["Unnamed: 0"],axis=1,inplace=True)
college_data.head()

Institute Name
Institute Code                                                   
1002                  Government College of Engineering, Amravati
1005                 Sant Gadge Baba Amravati University,Amravati
1012                     Government Engineering College, Yavatmal
1101            Shri Sant Gajanan Maharaj College of Engineeri...
1105            Prof. Ram Meghe Institute of Technology & Rese...

In [253]:
data=college_data.to_dict()
data=data['Institute Name']

In [254]:
dataframe["Institute Name"]=dataframe["college_code"].map(data)

In [255]:
dataframe.head()

Unnamed: 0.1.1  Sr.No.  Merit No  Marks  Application ID  \
0               0       1        60  95.13        19106856   
1               1       2       213  93.38        19126045   
2               2       3       384  92.47        19105661   
3               3       4       420  92.31        19103256   
4               4       5       846  90.79        19148502   

            Name of Candidate Gender Category PWD/DEF  Sub Group Seat Type  \
0  PAWAR SIDDHI RAVINDRASINGH      F     OPEN     NaN        201     LOPEN   
1   MAHALLE SHRADDHA MOHANRAO      F      OBC     NaN        201     GOPEN   
2        TUSHAR RAJESH LAHANE      M      OBC     NaN        201      GOBC   
3         RAUT PALASH SUBHASH      M      OBC     NaN        201      GOBC   
4   BIRAJDAR SAURABH DAYANAND      M     SEBC     NaN        201     GSEBC   

   cource_code  college_code  Category id  \
0          201          1002            1   
1          201          1002            2   
2          201          1002            2   
3          201          1002            2   
4          201          1002            3   

                                Institute Name  
0  Government College of Engineering, Amravati  
1  Government College of Engineering, Amravati  
2  Government College of Engineering, Amravati  
3  Government College of Engineering, Amravati  
4  Government College of Engineering, Amravati

###  College city

In [256]:
city=pd.read_csv("../final data/college town.csv",index_col=["Institute Code"])
city.drop(["Unnamed: 0"],axis=1,inplace=True)
city.head()

Institute dict
Institute Code               
1002                 Amravati
1005                 Amravati
1012                 Yavatmal
1101                 Buldhana
1105                 Amravati

In [257]:
dataframe["Institute dict"]=np.nan
city=city.to_dict()
city=city["Institute dict"]
dataframe["Institute dict"]=dataframe["college_code"].map(city)

In [258]:
dataframe.head()

Unnamed: 0.1.1  Sr.No.  Merit No  Marks  Application ID  \
0               0       1        60  95.13        19106856   
1               1       2       213  93.38        19126045   
2               2       3       384  92.47        19105661   
3               3       4       420  92.31        19103256   
4               4       5       846  90.79        19148502   

            Name of Candidate Gender Category PWD/DEF  Sub Group Seat Type  \
0  PAWAR SIDDHI RAVINDRASINGH      F     OPEN     NaN        201     LOPEN   
1   MAHALLE SHRADDHA MOHANRAO      F      OBC     NaN        201     GOPEN   
2        TUSHAR RAJESH LAHANE      M      OBC     NaN        201      GOBC   
3         RAUT PALASH SUBHASH      M      OBC     NaN        201      GOBC   
4   BIRAJDAR SAURABH DAYANAND      M     SEBC     NaN        201     GSEBC   

   cource_code  college_code  Category id  \
0          201          1002            1   
1          201          1002            2   
2          201          1002            2   
3          201          1002            2   
4          201          1002            3   

                                Institute Name Institute dict  
0  Government College of Engineering, Amravati       Amravati  
1  Government College of Engineering, Amravati       Amravati  
2  Government College of Engineering, Amravati       Amravati  
3  Government College of Engineering, Amravati       Amravati  
4  Government College of Engineering, Amravati       Amravati

In [259]:
dataframe=dataframe[["Merit No","Marks","Application ID","Name of Candidate","Gender","Category","Category id","Seat Type","PWD/DEF","Sub Group","cource_code","college_code","Institute dict","Institute Name"]]

In [260]:
dataframe.head()

Merit No  Marks  Application ID           Name of Candidate Gender  \
0        60  95.13        19106856  PAWAR SIDDHI RAVINDRASINGH      F   
1       213  93.38        19126045   MAHALLE SHRADDHA MOHANRAO      F   
2       384  92.47        19105661        TUSHAR RAJESH LAHANE      M   
3       420  92.31        19103256         RAUT PALASH SUBHASH      M   
4       846  90.79        19148502   BIRAJDAR SAURABH DAYANAND      M   

  Category  Category id Seat Type PWD/DEF  Sub Group  cource_code  \
0     OPEN            1     LOPEN     NaN        201          201   
1      OBC            2     GOPEN     NaN        201          201   
2      OBC            2      GOBC     NaN        201          201   
3      OBC            2      GOBC     NaN        201          201   
4     SEBC            3     GSEBC     NaN        201          201   

   college_code Institute dict                               Institute Name  
0          1002       Amravati  Government College of Engineering, Amravati  
1          1002       Amravati  Government College of Engineering, Amravati  
2          1002       Amravati  Government College of Engineering, Amravati  
3          1002       Amravati  Government College of Engineering, Amravati  
4          1002       Amravati  Government College of Engineering, Amravati

In [261]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73402 entries, 0 to 73401
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Merit No           73402 non-null  int64  
 1   Marks              73402 non-null  float64
 2   Application ID     73402 non-null  int64  
 3   Name of Candidate  73402 non-null  object 
 4   Gender             73402 non-null  object 
 5   Category           45738 non-null  object 
 6   Category id        73402 non-null  int64  
 7   Seat Type          73402 non-null  object 
 8   PWD/DEF            89 non-null     object 
 9   Sub Group          73402 non-null  int64  
 10  cource_code        73402 non-null  int64  
 11  college_code       73402 non-null  int64  
 12  Institute dict     45738 non-null  object 
 13  Institute Name     45738 non-null  object 
dtypes: float64(1), int64(6), object(7)
memory usage: 7.8+ MB


In [262]:
dataframe.to_csv("../reserch data/cap-2.csv")