# Data Cleaning

In [31]:
import pandas as pd
import numpy as np

In [32]:
dataframe=pd.read_csv("../final data/cap-1 student info.csv")
dataframe.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Sr.No. Merit No   Marks  \
0           0             0               0       1       60  95.13%   
1           1             1               1       2      213  93.38%   
2           2             2               2       3      384  92.47%   
3           3             3               3       4      420  92.31%   
4           4             4               4       5      846  90.79%   

  Application ID           Name of Candidate Gender Category PWD/DEF  \
0    DSE19106856  PAWAR SIDDHI RAVINDRASINGH      F     OPEN     NaN   
1    DSE19126045   MAHALLE SHRADDHA MOHANRAO      F      OBC     NaN   
2    DSE19105661        TUSHAR RAJESH LAHANE      M      OBC     NaN   
3    DSE19103256         RAUT PALASH SUBHASH      M      OBC     NaN   
4    DSE19148502   BIRAJDAR SAURABH DAYANAND      M     SEBC     NaN   

  Sub Group Seat Type  cource_code  college_code  
0       201    ^LOPEN          201          1002  
1       201    ^GOPEN          201          1002  
2       201     #GOBC          201          1002  
3       201     ^GOBC          201          1002  
4       201    *GSEBC          201          1002

In [33]:
dataframe.drop(["Unnamed: 0","Unnamed: 0.1","Unnamed: 0.1.1"],axis=1,inplace=True)

## Feature clearing

### Feature ["Mert No"]

Marks have some vacant anoted by "-" they showd be convertd as 0  

In [34]:
dataframe["Merit No"]=dataframe["Merit No"].astype(str)
vacent_entres=dataframe[dataframe["Merit No"]=="-"].index.values
dataframe.iloc[vacent_entres]=0

The feature mert no have all the integer feature it shoud be integer

In [35]:
dataframe["Merit No"] = pd.to_numeric(dataframe["Merit No"], errors='coerce').fillna(0).astype(np.int64)

### Feature [Marks]

The marks in format of % eg 80.0% they should converted as 80.0 

In [36]:
dataframe["Marks"]=dataframe["Marks"].astype(str)

In [37]:
length=dataframe.shape
length[0]

75031

removig %

In [38]:
for i in range(length[0]):
    data=dataframe["Marks"].iloc[i]
    if data!=0:
        data=''.join([ word for word  in data if word.isdigit() or word=="."])
        dataframe["Marks"].iloc[i]=data

C:\Users\sai\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


In [39]:
dataframe["Marks"] = pd.to_numeric(dataframe["Marks"], errors='coerce').fillna(0).astype(np.float64)

### Feature [Application Id]

The application id is only the feature that can uniqly identify student bot the application id is in format DSE12458. if move remove [DSE] from the if goood o have id as Integer

In [40]:
dataframe["Application ID"]=dataframe["Application ID"].astype(str)

In [41]:
for i in range(length[0]):
    data=dataframe["Application ID"].iloc[i]
    if  data !=0:
        data=''.join([word for word in data if  word.isdigit()])
        dataframe["Application ID"].iloc[i]=data

In [42]:
dataframe["Application ID"] = pd.to_numeric(dataframe["Application ID"], errors='coerce').fillna(0).astype(np.int64)

### Feature [Seat Type]

The feature seat type contain the spacial symobols witch can affect model.It better to remove the symboles

In [43]:
dataframe["Seat Type"]=dataframe["Seat Type"].astype(str)

In [44]:
for i in range(length[0]):
    data=dataframe["Seat Type"].iloc[i]
    if data!=0:
        data=''.join([word for word in data if word.isalpha()])
        dataframe["Seat Type"].iloc[i]=data

In [45]:
dataframe["Seat Type"].unique()

array(['LOPEN', 'GOPEN', 'GOBC', 'GSEBC', 'LSC', 'EWS', 'LST', 'GSC', '',
       'LOBC', 'GST', 'GNTD', 'LSEBC', 'LNTC', 'PHOBC', 'LNTB', 'MI',
       'GNTB', 'GNTC', 'GNTA', 'LNTA', 'DFSC', 'LNTD', 'PHO', 'DFSEBC',
       'DFO', 'PHSC', 'DFOBC', 'DFNTC', 'DFNTD', 'PHNTC', 'PHSEBC',
       'PHNTB', 'PHNTA', 'DFST', 'DFNTB', 'PHNTD'], dtype=object)

### Feature [Category]

The feature invalid symboles

In [46]:
for i in range(length[0]):
    data=dataframe["Category"].iloc[i]
    if data!=0:
        data=''.join([word for word in data if word.isalpha() or word.isdigit() or word == "/" or word=="(" or word==")"])
        dataframe["Category"].iloc[i]=data

In [47]:
dataframe["Category"].unique()

array(['OPEN', 'OBC', 'SEBC', 'SC', 'OPEN/EWS', 'ST', 'NT1(NTB)', 0,
       'NT3(NTD)', 'NT2(NTC)', 'SBC/OBC', 'DT/VJNT(A)', 'SBC', '0'],
      dtype=object)

In [48]:
category_unique=dict({
    "OPEN":"OPEN",
    "OBC":"OBC",
    "SEBC":"SEBC",
    "SC":"SC",
    "OPEN/EWS":"OPEN/EWS",
    "ST":"ST",
    "NT1(NTB)":"NT1",
    "NT2(NTC)":"NT2",
    "NT3(NTD)":"NT3",
    "SBC/OBC":"SBC/OBC",
    "DT/VJNT(A)":"DT/VJNT(A)",
    "SBC":"SBC"
})

dataframe["Category"]=dataframe["Category"].map(category_unique)

In [49]:
dataframe["Category"].unique()

array(['OPEN', 'OBC', 'SEBC', 'SC', 'OPEN/EWS', 'ST', 'NT1', nan, 'NT3',
       'NT2', 'SBC/OBC', 'DT/VJNT(A)', 'SBC'], dtype=object)

In [50]:
category_unique=dict({
    "OPEN":1,
    "OBC":2,
    "SEBC":3,
    "SC":4,
    "OPEN/EWS":5,
    "ST":6,
    "NT1":7,
    "NT2":8,
    "NT3":9,
    "SBC/OBC":10,
    "DT/VJNT(A)":11,
    "SBC":12
})
dataframe["Category id"]=dataframe["Category"].map(category_unique)

In [68]:
dataframe["Category id"] = pd.to_numeric(dataframe["Category id"], errors='coerce').fillna(0).astype(np.int64)

In [51]:
dataframe["Category id"].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7., nan,  9.,  8., 10., 11., 12.])

###  Feature [Gender]

In [52]:
dataframe["Gender"]=dataframe["Gender"].astype(str)

### Feature [PWD/DEF]

PWD/DEF invalis carater such as /n /r

In [53]:
dataframe["PWD/DEF"].unique()

array([nan, 0, 'Low-Vision', 'DEF1', 'Locomotor \r\nDisability',
       'Physical \r\nimpairment', 'DEF2', 'Hard of \r\nHearing',
       'Thalassemia', '0', 'Specific \r\nLearning \r\nDisabilities',
       'Cerebral \r\nPalsy', 'Blindness', 'DEF3', 'Haemophilia',
       'Muscular \r\nDystrophy', 'Physical \r\nimpairment/DEF1', 'Deaf',
       'Intellectual \r\nDisability'], dtype=object)

In [64]:
pwd_def=dict({
  "Locomotor \r\nDisability":"Locomotor Disability",
  "Physical \r\nimpairment":"Physical impairment",
  "Hard of \r\nHearing":"Hard of Hearing",
  "Specific \r\nLearning \r\nDisabilities":"Specific Learning Disabilities",
  "Cerebral \r\nPalsy":"Cerebral Palsy",
  "Muscular \r\nDystrophy":"Muscular Dystrophy",
  "Physical \r\nimpairment/DEF1":"Physical impairment DEF1",
  "Intellectual \r\nDisability":"Intellectual Disability"
})
dataframe["PWD/DEF"]=dataframe["PWD/DEF"].map(pwd_def)

In [65]:
dataframe["PWD/DEF"].unique()

array([nan, 'Locomotor Disability', 'Physical impairment',
       'Hard of Hearing', 'Specific Learning Disabilities',
       'Cerebral Palsy', 'Muscular Dystrophy', 'Physical impairment DEF1',
       'Intellectual Disability'], dtype=object)

### Feature [Sub Group]

In [81]:
str1="0402"
str1[]

''

### Add College Name

The data scource only have college code we have to add collage name

In [56]:
college_data=pd.read_csv("../final data/college maping.csv",index_col=["Institute Code"],usecols=None,)
college_data.drop(["Unnamed: 0"],axis=1,inplace=True)
college_data.head()

Institute Name
Institute Code                                                   
1002                  Government College of Engineering, Amravati
1005                 Sant Gadge Baba Amravati University,Amravati
1012                     Government Engineering College, Yavatmal
1101            Shri Sant Gajanan Maharaj College of Engineeri...
1105            Prof. Ram Meghe Institute of Technology & Rese...

In [57]:
data=college_data.to_dict()
data=data['Institute Name']

In [58]:
dataframe["Institute Name"]=dataframe["college_code"].map(data)

In [59]:
dataframe.head()

Sr.No.  Merit No  Marks  Application ID           Name of Candidate Gender  \
0       1        60  95.13        19106856  PAWAR SIDDHI RAVINDRASINGH      F   
1       2       213  93.38        19126045   MAHALLE SHRADDHA MOHANRAO      F   
2       3       384  92.47        19105661        TUSHAR RAJESH LAHANE      M   
3       4       420  92.31        19103256         RAUT PALASH SUBHASH      M   
4       5       846  90.79        19148502   BIRAJDAR SAURABH DAYANAND      M   

  Category PWD/DEF Sub Group Seat Type  cource_code  college_code  \
0     OPEN     NaN       201     LOPEN          201          1002   
1      OBC     NaN       201     GOPEN          201          1002   
2      OBC     NaN       201      GOBC          201          1002   
3      OBC     NaN       201      GOBC          201          1002   
4     SEBC     NaN       201     GSEBC          201          1002   

   Category id                               Institute Name  
0          1.0  Government College of Engineering, Amravati  
1          2.0  Government College of Engineering, Amravati  
2          2.0  Government College of Engineering, Amravati  
3          2.0  Government College of Engineering, Amravati  
4          3.0  Government College of Engineering, Amravati

###  College city

In [60]:
city=pd.read_csv("../final data/college town.csv",index_col=["Institute Code"])
city.drop(["Unnamed: 0"],axis=1,inplace=True)
city.head()

Institute dict
Institute Code               
1002                 Amravati
1005                 Amravati
1012                 Yavatmal
1101                 Buldhana
1105                 Amravati

In [61]:
dataframe["Institute dict"]=np.nan
city=city.to_dict()
city=city["Institute dict"]
dataframe["Institute dict"]=dataframe["college_code"].map(city)

In [62]:
dataframe.head()

Sr.No.  Merit No  Marks  Application ID           Name of Candidate Gender  \
0       1        60  95.13        19106856  PAWAR SIDDHI RAVINDRASINGH      F   
1       2       213  93.38        19126045   MAHALLE SHRADDHA MOHANRAO      F   
2       3       384  92.47        19105661        TUSHAR RAJESH LAHANE      M   
3       4       420  92.31        19103256         RAUT PALASH SUBHASH      M   
4       5       846  90.79        19148502   BIRAJDAR SAURABH DAYANAND      M   

  Category PWD/DEF Sub Group Seat Type  cource_code  college_code  \
0     OPEN     NaN       201     LOPEN          201          1002   
1      OBC     NaN       201     GOPEN          201          1002   
2      OBC     NaN       201      GOBC          201          1002   
3      OBC     NaN       201      GOBC          201          1002   
4     SEBC     NaN       201     GSEBC          201          1002   

   Category id                               Institute Name Institute dict  
0          1.0  Government College of Engineering, Amravati       Amravati  
1          2.0  Government College of Engineering, Amravati       Amravati  
2          2.0  Government College of Engineering, Amravati       Amravati  
3          2.0  Government College of Engineering, Amravati       Amravati  
4          3.0  Government College of Engineering, Amravati       Amravati

In [69]:
dataframe=dataframe[["Merit No","Marks","Application ID","Name of Candidate","Gender","Category","Category id","Seat Type","PWD/DEF","Sub Group","cource_code","college_code","Institute dict","Institute Name"]]

In [70]:
dataframe.head()

Merit No  Marks  Application ID           Name of Candidate Gender  \
0        60  95.13        19106856  PAWAR SIDDHI RAVINDRASINGH      F   
1       213  93.38        19126045   MAHALLE SHRADDHA MOHANRAO      F   
2       384  92.47        19105661        TUSHAR RAJESH LAHANE      M   
3       420  92.31        19103256         RAUT PALASH SUBHASH      M   
4       846  90.79        19148502   BIRAJDAR SAURABH DAYANAND      M   

  Category  Category id Seat Type PWD/DEF Sub Group  cource_code  \
0     OPEN            1     LOPEN     NaN       201          201   
1      OBC            2     GOPEN     NaN       201          201   
2      OBC            2      GOBC     NaN       201          201   
3      OBC            2      GOBC     NaN       201          201   
4     SEBC            3     GSEBC     NaN       201          201   

   college_code Institute dict                               Institute Name  
0          1002       Amravati  Government College of Engineering, Amravati  
1          1002       Amravati  Government College of Engineering, Amravati  
2          1002       Amravati  Government College of Engineering, Amravati  
3          1002       Amravati  Government College of Engineering, Amravati  
4          1002       Amravati  Government College of Engineering, Amravati

In [71]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75031 entries, 0 to 75030
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Merit No           75031 non-null  int64  
 1   Marks              75031 non-null  float64
 2   Application ID     75031 non-null  int64  
 3   Name of Candidate  75031 non-null  object 
 4   Gender             75031 non-null  object 
 5   Category           38927 non-null  object 
 6   Category id        75031 non-null  int64  
 7   Seat Type          75031 non-null  object 
 8   PWD/DEF            81 non-null     object 
 9   Sub Group          75031 non-null  object 
 10  cource_code        75031 non-null  int64  
 11  college_code       75031 non-null  int64  
 12  Institute dict     38927 non-null  object 
 13  Institute Name     38927 non-null  object 
dtypes: float64(1), int64(5), object(8)
memory usage: 8.0+ MB


In [72]:
dataframe["Sub Group"].unique()

array(['201', '0101', '0104', 0, '101', '0102', '0401', '0103', '102',
       '0701', '0404', '0201', '0702', '103', '104', '0304', '0302',
       '302', '401', '301', '0301', '0', '201.0', '301.0', '304', '701',
       '0303', '0501', '303', '0305', '702', '305', '0402', '402', '0403',
       '404', '0801', '501', '601', '0601'], dtype=object)