# Data Cleaning

In [2]:
import pandas as pd
import numpy as np

In data minig it is found that some rows have shifted to left there are less number off rows with are shifted so just drop it

In [23]:
dataframe=pd.read_csv("../final data/Cap-2 Student Info.csv")
dataframe.head()

Unnamed: 0 Sr.No. Merit No   Marks Application ID  \
0           0    1.0       60  95.13%    DSE19106856   
1           1    2.0      213  93.38%    DSE19126045   
2           2    3.0      384  92.47%    DSE19105661   
3           3    4.0      420  92.31%    DSE19103256   
4           4    5.0      846  90.79%    DSE19148502   

            Name of Candidate Gender Category PWD/DEF Sub Group Seat Type  \
0  PAWAR SIDDHI RAVINDRASINGH      F     OPEN     NaN       201    ^LOPEN   
1   MAHALLE SHRADDHA MOHANRAO      F      OBC     NaN       201    ^GOPEN   
2        TUSHAR RAJESH LAHANE      M      OBC     NaN       201     #GOBC   
3         RAUT PALASH SUBHASH      M      OBC     NaN       201     ^GOBC   
4   BIRAJDAR SAURABH DAYANAND      M     SEBC     NaN       201    *GSEBC   

   cource_code  college_code  
0          201          1002  
1          201          1002  
2          201          1002  
3          201          1002  
4          201          1002

In [19]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73813 entries, 0 to 73812
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Unnamed: 0         73813 non-null  int64 
 1   Sr.No.             73787 non-null  object
 2   Merit No           73787 non-null  object
 3   Marks              73787 non-null  object
 4   Application ID     73787 non-null  object
 5   Name of Candidate  73787 non-null  object
 6   Gender             73787 non-null  object
 7   Category           73213 non-null  object
 8   PWD/DEF            975 non-null    object
 9   Sub Group          73787 non-null  object
 10  Seat Type          73211 non-null  object
 11  cource_code        73813 non-null  int64 
 12  college_code       73813 non-null  int64 
dtypes: int64(3), object(10)
memory usage: 7.3+ MB


In [26]:
dataframe["Sr.No."].unique()

array([    1,     2,     3,     4,     5,     6,     7,     8,     9,
          10,    11,    12,    13,    14,    15,    16,    17,    18,
          19,    20,    21,    22,    23,    24,    25,    26,    27,
          28,    29,    30,    31,    32,    33,    34,    35,    36,
          37,    38,    39,    40,    41,    42,    43,    44,    45,
          46,    47,    48,    49,    50,    51,    52,    53,    54,
          55,    56,    57,    58,    59,    60,    61,    62,    63,
          64,    65,    66,    67,    68,    69,    71,    72,    73,
          74,    75,    76,    77,    78,    79,    80,    81,    82,
          83,    84,    85,    86,     0,    87,    88,    89,    90,
          91,    92,    93,    94,    95,    96,    97,    98,    99,
         100,   101,   102,   103,   104,   105,   106,   107,   108,
         109,   110,   111,   113,   114,   115,   116,   117,   118,
         119,   120,   121,   122,   123,   124,   125,    70,   126,
         127,   128,

In [123]:
dataframe.shape

(75159, 13)

In [124]:
vacent_record=dataframe[dataframe["Sr.No."]=="-"].index.values
vacent_record_nan=dataframe[dataframe["Sr.No."].isnull()].index.values

In [125]:
len(vacent_record_nan)

42

In [126]:
dataframe.iloc[vacent_record]=0
dataframe.iloc[vacent_record_nan]=0

In [127]:
dataframe.head()

Unnamed: 0 Sr.No. Merit No   Marks Application ID  \
0           0      1       60  95.13%    DSE19106856   
1           1      2      213  93.38%    DSE19126045   
2           2      3      384  92.47%    DSE19105661   
3           3      4      420  92.31%    DSE19103256   
4           4      5      846  90.79%    DSE19148502   

            Name of Candidate Gender Category PWD/DEF Sub Group Seat Type  \
0  PAWAR SIDDHI RAVINDRASINGH      F     OPEN     NaN       201    ^LOPEN   
1   MAHALLE SHRADDHA MOHANRAO      F      OBC     NaN       201    ^GOPEN   
2        TUSHAR RAJESH LAHANE      M      OBC     NaN       201     #GOBC   
3         RAUT PALASH SUBHASH      M      OBC     NaN       201     ^GOBC   
4   BIRAJDAR SAURABH DAYANAND      M     SEBC     NaN       201    *GSEBC   

   cource_code  college_code  
0          201          1002  
1          201          1002  
2          201          1002  
3          201          1002  
4          201          1002

In [131]:
invalid=['102', '103', '104', '105', '106', '107', '108', '109', '110',
       '111', '113', '114', '115', '116', '117', '118', '119', '120',
       '121', '122', '123', '124', '125', '70', '46539', 0, '126', '127',
       '128', '129', '130', '131', '132', '133', '134', '1.0', '2.0',
       '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0',
       '12.0', '13.0', '14.0', '15.0', '16.0', '17.0', '18.0', '19.0',
       '20.0', '21.0', '22.0', '23.0', '24.0', '25.0', '26.0', '27.0',
       '29.0', '30.0', '31.0', '32.0', '33.0', '34.0', '35.0', '36.0',
       '37.0', '38.0', '39.0', '40.0', '41.0', '42.0', '43.0', '44.0',
       '45.0', '46.0', '47.0', '48.0', '49.0', '50.0', '51.0', '52.0',
       '53.0', '54.0', '55.0', '56.0', '57.0', '58.0', '59.0', '60.0',
       '61.0', '3515.0', '3953.0', '4224.0', '5357.0', '6067.0', '6582.0',
       '6643.0', '7540.0', '7594.0', '8225.0', '8636.0', '10558.0',
       '28.0', '8286', '11461', '22704', '45053', '53591', '24816',
       '44680', '45620', '52483', '135', '39233', '47755', '24904',
       '27431', '33788', '112', '26923', '24478', '4374', '13223',
       '13545', '14415', '14657', '16081', '16401', '17042', '23430',
       '30785', '36462', '39421', '40771', '41739', '43076', '43735',
       '45042', '47059', '7912', '21698', '47390', '51634', '52954',
       '53648', '54148', '136', '137', '138', '139', '140', '141', '142',
       '143', '144', '145', '146', '147', '148', '149', '150', '151',
       '152', '153', '154', '155', '156', '157', '158', '159', '161',
       '162', '163', '164', '165', '166', '167', '168', '169', '170',
       '171', '172', '173', '174', '175', '176', '177', '178', '179',
       '180', '181', '182', '183', '184', '185', '186', '187', '188',
       '189', '190', '191', '192', '193', '194', '195', '196', '197',
       '198', '199', '200', '201', '203', '204', '205', '206', '207',
       '208', '209', '210', '211', '212', '213', '214', '17660', '28356',
       '28633', '28737', '28895', '29405', '32055', '32298', '37037',
       '42063', '42095', '42365', '46280', '46777', '46857', '46895',
       '47317', '49800', '49983', '54081', '54122', '54203', '28956',
       '29239', '30243', '30754', '30932', '32399', '32819', '32907',
       '34643', '36684', '41214', '42673', '42932', '47562', '47993',
       '48701', '51766', '53091', '54305', '43603', '7993', '9970',
       '10604', '13637', '17120', '21268', '25022', '27056', '27131',
       '30557', '31721', '34912', '38730', '38858', '38877', '40234',
       '43104', '43471', '46598', '46833', '47251', '48570', '5747',
       '12953', '32357', '40137', '43102', '49157', '43824', '45250',
       '47375', '47763', '215', '216', '217', '218', '219', '220', '221',
       '222', '223', '224', '225', '226', '227', '228', '229', '230',
       '231', '232', '233', '234', '235', '236', '237', '238', '239',
       '240', '241', '242', '243']

In [145]:
shifted_record=[]
for srno in range(0,len(invalid)):
    shifted_record.append(dataframe[dataframe["Sr.No."]==invalid[srno]].index.values)

In [149]:
shifted_record[0]

array([ 1213,  1733,  3416,  3855,  4627,  5920,  6305,  7201,  7413,
        8153,  8442,  8605,  9111, 10464, 11857, 12583, 12754, 23054,
       24201, 25821, 26015, 26146, 27530, 27764, 31178, 36263, 36448,
       36751, 37021, 37316, 37505, 38263, 39342, 40710, 40872, 42736,
       43440, 45100, 46363, 46925, 47524, 47966, 52065, 52772, 53053,
       53346, 53602, 54095, 54434, 56348, 56469, 56671, 57329, 57591,
       59258, 59412, 59811, 59915, 60055, 61079, 61340, 61726, 61851,
       62444, 62769, 64071, 64182, 64410, 65116, 65231, 65337, 65501,
       65781, 65908, 66146, 66277, 66516, 66775, 67872, 68017, 68223,
       68757, 69167, 69512, 69858, 70042, 70156, 70269, 70640, 70827,
       71014, 71321, 71564, 72000, 72175, 72361, 72493, 72625, 72817,
       72947, 73260, 73752, 73911, 74105, 74225, 74874], dtype=int64)

In [25]:
dataframe["Sr.No."] = pd.to_numeric(dataframe["Sr.No."], errors='coerce').fillna(0).astype(np.int64)

In [129]:
dataframe["Sr.No."]=dataframe["Sr.No."].astype(int)

ValueError: invalid literal for int() with base 10: '1.0'

In [164]:
print(dataframe[dataframe["Sr.No."]=="2.0"].index.values)

[4095 4156 8956]


In [6]:
dataframe.iloc[4094:4099]

Unnamed: 0 Sr.No. Merit No   Marks Application ID  \
4094        4094    1.0   3940.0  85.64%    DSE19106379   
4095        4095    2.0   9603.0  80.30%    DSE19137667   
4096        4096    3.0  10120.0  79.88%    DSE19129396   
4097        4097    4.0  23967.0  71.39%    DSE19115389   
4098        4098    5.0  26231.0  70.30%    DSE19115310   

             Name of Candidate Gender Category PWD/DEF Sub Group Seat Type  \
4094     SHINDE PADMAJA GANESH      F     SEBC     NaN     201.0     LOPEN   
4095    DALVI ASHWITA NARENDRA      F      OBC     NaN     201.0     LOPEN   
4096      PATIL ADITI RAJENDRA      F      OBC     NaN     201.0     LOPEN   
4097    GAIKWAD KUNAL SUDHAKAR      M      OBC     NaN     201.0     GOPEN   
4098  DESHMUKH SANKET HARIBHAU      M     SEBC     NaN     201.0     GOPEN   

      cource_code  college_code  
4094          201          3447  
4095          201          3447  
4096          201          3447  
4097          201          3447  
4098          201          3447